### ISSUE TITLE
关于evaluate.py运行的问题

### ISSUE THREAD

**Issue by jhgfkdj** [bluer555/CR-GAN#3]
您好，
我的运行环境是cuda8 + pytorch 0.4.1，如果按照你的测试demo中的例子来跑则出现cuda版本不满足runtime版本的要求，由于我的环境还有tensorflow1.4因此cuda不可升级。
因此我尝试使用cpu来跑你的demo，我修改了--cuda中默认位False，并在load_pretrained_model()中修改了torch.load()中的参数：
state_dict = torch.load('%s/%s' % (path,name), map_location=lambda storage, loc: storage)
然而这样的话则输出一系列not load：
not load weights module.conv.weight
not load weights module.conv.bias
not load weights module.resBlock0.conv_shortcut.conv.weight
not load weights module.resBlock0.conv_shortcut.conv.bias
not load weights module.resBlock0.conv1.weight
……
还是这个函数中，own_state[name].copy_(param)的作用是什么呢？复制state_dict中的param到own_state中吗？然后own_state这个字典的作用是什么呢？
最后在evalueate文件夹中生成的图片则是只有第一张原图其他置灰的图像，这肯定是不正确的对吧？

**Comment by bluer555** [comment]
您好，pre-trained model是在gpu模式下训练的，所以evaluate.py中先G_xvz = torch.nn.DataParallel(G_xvz).cuda()，再读入gpu模式下训练好的模型，如果不是gpu模式的话那么就会读取模型失败。我的环境是cuda8 + pytorch 0.3.1

**Comment by jhgfkdj** [comment]
@bluer555 谢谢，我把pytorch降级与你一样版本后的确跑通了你的测试图片，但是如果我用自己的图片来做测试的话，结果输出完全是紊乱的，请问是需要对图片做哪些预处理吗？

**Comment by bluer555** [comment]
能看下你的图片什么样吗

**Comment by jhgfkdj** [comment]
@bluer555 这个是用我自己的iphone7Plus拍摄的一个3024x4032大小的亚洲人脸，白色背景，正面戴眼镜照。如果您能提供一个私信通道我可以给您看我的原图和用您的算法跑出来的结果。

**Comment by bluer555** [comment]
您好 我的gmail是tianyu0124@gmail.com
