### ISSUE TITLE
How to train this project and something occur after operating python train.py

### ISSUE THREAD

**Issue by Huang9495** [bluer555/CR-GAN#4]
I use two datasets to train includes crop_0907 and multi_PIE_crop_128, Before I input `python train.py` according the Readme. Meanwhile I modify somewhere in the train.py as fellow:

**First:** parser.add_argument('--modelf', default='./model', help='folder to output images and model checkpoints')(I push the pretraining model in this dir );
**Second:** I modify the path and name of model
Iload_model(G_xvz, args.modelf, 'netG_xvz.pth')
load_model(G_vzx, args.modelf, 'netG_vzx.pth')
load_model(D_xvs, args.modelf, 'netD_xvs.pth')

Environment:
Linux 16.04;
python 2.7.12;
pytorch 0.3.1;

After I input `python train.py `. The terminal show load relative parameter and not go on. The picture is here: 
![screenshot from 2018-09-04 09-14-25](https://user-images.githubusercontent.com/26674689/45005357-70599e00-b025-11e8-84bd-f417d4c376c1.png)
 
And I want to know it's correct? I don't clearly know how to train the model in CR-GAN. Can you help me ? Thanks.

**Comment by bluer555** [comment]
I guess you have the same issue in another post, I'll fix it soon. 

Sorry for the inconvenience. I was using my own environment to test the codes, so didn't notice that problem.

**Comment by Huang9495** [comment]
@bluer555 I test you code and find the issue cause by while in get_300w_LP_img and it's
 the same as https://github.com/bluer555/CR-GAN/issues/2
